/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      textShadow: {
        'default': '0 0 5px rgba(255, 255, 255, 0.8)',
      }
    },
  },
  plugins: [],
  safelist: [
    'border-green-500',
    'border-yellow-500',
    'border-blue-500',
    'border-gray-500',
    'border-purple-500',
    'bg-blue-500',
    'bg-green-500',
    'bg-red-500',
    'bg-purple-500',
    'bg-yellow-500',
    'bg-orange-500',
    'bg-teal-500',
    'bg-indigo-500',
    'bg-pink-500',
    'bg-cyan-500',
    'bg-lime-500',
    'bg-emerald-500',
    'bg-gray-500',
    '✅',
    '🏖️',
    '📞',
    '🚫',
    '🏥',
    '🏦',
    '🚨',
    '💖',
    '1️⃣',
    '2️⃣',
    '3️⃣',
    '🌅',
    '🌃',
    '🌟',
    '✨',
    '📚',
    '🌙',
    '🦉',
    '📝',
    '🤝',
    'Stay Late 1',
    'Stay Late 2',
    'MRI EVENING CALL',
    'text-shadow-default',
  ],
};